### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by panna19951227** [tomar840/two-stream-average-fusion-for-action-recognition-in-videos#1]
I have been meeting a problem as follows,can you give me some advice?
![11](https://user-images.githubusercontent.com/39176743/41101729-8a54e68a-6a97-11e8-92ec-87dcfd595011.PNG)

**Comment by tomar840** [comment]
Hi @panna19951227 , 
I think the problem is with integeration of pytorch with anaconda. Try to install pytorch from different source.
