### ISSUE TITLE
Code is not the same as the network picture

### ISSUE THREAD

**Issue by jayceheo92** [tomar840/two-stream-average-fusion-for-action-recognition-in-videos#5]
Thanks for your code.

I got curious in "conv_fusion.py", especially the section of forwarding.

Unlike the picture, your training code doesn't consider layer manipulations
to get fused before linear layers. Of course, the code doesn't run.

Plus, there is no way to check or reproduce your result average.(no eval code)

It'll be great if you get the code modified just like the main page.

Again, Thanks.

**Comment by tomar840** [comment]
Hi @jayceheo92 , 
Yes, fusion of layers have been taken care in the code as well. Please go through the class **Net** in "conv_fusion.py".
